/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package viewer;

import control.FuncoesUteis;
import control.GerenciadorInterface;
import domain.Compra;
import domain.Endereco;
import domain.Pessoa;
import domain.Veiculo;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;

/**
 *
 * @author 2022122760044
 */
public class DlgCompra extends javax.swing.JDialog {

    /**
     * Creates new form DlgCadastrarCompra
     */
    public DlgCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipo = new javax.swing.ButtonGroup();
        bgCombustivel = new javax.swing.ButtonGroup();
        jpPrincipalCompra = new javax.swing.JPanel();
        jlTituloCompra = new javax.swing.JLabel();
        jtPainelCompra = new javax.swing.JTabbedPane();
        jpNovaCompra = new javax.swing.JPanel();
        jpVendedor = new javax.swing.JPanel();
        jlNomeVendedor = new javax.swing.JLabel();
        txtNumEndRevendedor = new javax.swing.JTextField();
        jlTelVendedor = new javax.swing.JLabel();
        txtTelRevendedor = new javax.swing.JFormattedTextField();
        jlNumEndVendedor = new javax.swing.JLabel();
        txtCepRevendedor = new javax.swing.JFormattedTextField();
        jlEndVendedor = new javax.swing.JLabel();
        txtDescEndereco = new javax.swing.JTextField();
        jlBairroVendedor = new javax.swing.JLabel();
        jlEstadoVendedor = new javax.swing.JLabel();
        jlCidadeVendedor = new javax.swing.JLabel();
        txtCidadeEnder = new javax.swing.JTextField();
        txtBairroEnder = new javax.swing.JTextField();
        jlCEPVendedor = new javax.swing.JLabel();
        txtNomeRevendedor = new javax.swing.JTextField();
        jpDataValorCompra = new javax.swing.JPanel();
        jlDataCompra = new javax.swing.JLabel();
        txtDataCompra = new javax.swing.JFormattedTextField();
        jlValorCompra = new javax.swing.JLabel();
        txtValorCompra = new javax.swing.JTextField();
        txtEstadoEnd = new javax.swing.JTextField();
        jlCEPVendedor1 = new javax.swing.JLabel();
        txtCpfRevendedor = new javax.swing.JFormattedTextField();
        jpVeiculo = new javax.swing.JPanel();
        jlPlacaVeiculoCompra = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jlRenavamVeiculoCompra = new javax.swing.JLabel();
        txtRenavam = new javax.swing.JTextField();
        jlMarcaVeiculoCompra = new javax.swing.JLabel();
        jlModeloVeiculoCompra = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        jlAnoVeiculoCompra = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        jpTipoVeiculoCompra = new javax.swing.JPanel();
        jrbCarro = new javax.swing.JRadioButton();
        jrbMoto = new javax.swing.JRadioButton();
        jlCorVeiculoCompra = new javax.swing.JLabel();
        cmbCor = new javax.swing.JComboBox<>();
        jpCombustivelVeiculoCompra = new javax.swing.JPanel();
        jrbGasolina = new javax.swing.JRadioButton();
        jrbDiesel = new javax.swing.JRadioButton();
        jrbEtanol = new javax.swing.JRadioButton();
        jrbGas = new javax.swing.JRadioButton();
        jrbFlex = new javax.swing.JRadioButton();
        jrbEletrico = new javax.swing.JRadioButton();
        jrbHibrido = new javax.swing.JRadioButton();
        jbRegistrarCompra = new javax.swing.JButton();
        jpListaVeiculosComprados = new javax.swing.JPanel();
        jsListaVeiculosComprados = new javax.swing.JScrollPane();
        jtListaVeiculosComprados = new javax.swing.JTable();
        jlPlacaFiltroDespesas = new javax.swing.JLabel();
        jtPlacaFiltroDespesas = new javax.swing.JTextField();
        jbPesquisarFiltroDespesas = new javax.swing.JButton();
        jbListarFiltroDespesas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ficha de Entrada");
        setPreferredSize(new java.awt.Dimension(1020, 750));
        setResizable(false);

        jpPrincipalCompra.setBackground(new java.awt.Color(255, 255, 102));
        jpPrincipalCompra.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        jpPrincipalCompra.setPreferredSize(new java.awt.Dimension(1000, 700));

        jlTituloCompra.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jlTituloCompra.setForeground(new java.awt.Color(0, 0, 0));
        jlTituloCompra.setText("FICHA DE ENTRADA");

        jtPainelCompra.setBackground(new java.awt.Color(0, 0, 0));
        jtPainelCompra.setForeground(new java.awt.Color(255, 255, 255));
        jtPainelCompra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtPainelCompra.setMinimumSize(new java.awt.Dimension(91, 60));
        jtPainelCompra.setPreferredSize(new java.awt.Dimension(978, 632));

        jpNovaCompra.setBackground(new java.awt.Color(255, 255, 102));
        jpNovaCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpNovaCompra.setForeground(new java.awt.Color(0, 0, 0));

        jpVendedor.setBackground(new java.awt.Color(255, 255, 102));
        jpVendedor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Revendedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24), new java.awt.Color(0, 0, 0))); // NOI18N

        jlNomeVendedor.setBackground(new java.awt.Color(0, 0, 0));
        jlNomeVendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlNomeVendedor.setForeground(new java.awt.Color(0, 0, 0));
        jlNomeVendedor.setText("Nome Completo:");

        txtNumEndRevendedor.setBackground(new java.awt.Color(204, 204, 204));
        txtNumEndRevendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNumEndRevendedor.setForeground(new java.awt.Color(0, 0, 0));
        txtNumEndRevendedor.setBorder(new javax.swing.border.MatteBorder(null));

        jlTelVendedor.setBackground(new java.awt.Color(0, 0, 0));
        jlTelVendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlTelVendedor.setForeground(new java.awt.Color(0, 0, 0));
        jlTelVendedor.setText("Telefone:");

        txtTelRevendedor.setBackground(new java.awt.Color(204, 204, 204));
        txtTelRevendedor.setBorder(new javax.swing.border.MatteBorder(null));
        txtTelRevendedor.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtTelRevendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelRevendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jlNumEndVendedor.setBackground(new java.awt.Color(0, 0, 0));
        jlNumEndVendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlNumEndVendedor.setForeground(new java.awt.Color(0, 0, 0));
        jlNumEndVendedor.setText("Nº:");

        txtCepRevendedor.setBackground(new java.awt.Color(204, 204, 204));
        txtCepRevendedor.setBorder(new javax.swing.border.MatteBorder(null));
        txtCepRevendedor.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtCepRevendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCepRevendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jlEndVendedor.setBackground(new java.awt.Color(0, 0, 0));
        jlEndVendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlEndVendedor.setForeground(new java.awt.Color(0, 0, 0));
        jlEndVendedor.setText("Endereço:");

        txtDescEndereco.setBackground(new java.awt.Color(204, 204, 204));
        txtDescEndereco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDescEndereco.setForeground(new java.awt.Color(0, 0, 0));
        txtDescEndereco.setBorder(new javax.swing.border.MatteBorder(null));

        jlBairroVendedor.setBackground(new java.awt.Color(0, 0, 0));
        jlBairroVendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlBairroVendedor.setForeground(new java.awt.Color(0, 0, 0));
        jlBairroVendedor.setText("Bairro:");

        jlEstadoVendedor.setBackground(new java.awt.Color(0, 0, 0));
        jlEstadoVendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlEstadoVendedor.setForeground(new java.awt.Color(0, 0, 0));
        jlEstadoVendedor.setText("Estado:");

        jlCidadeVendedor.setBackground(new java.awt.Color(0, 0, 0));
        jlCidadeVendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlCidadeVendedor.setForeground(new java.awt.Color(0, 0, 0));
        jlCidadeVendedor.setText("Cidade:");

        txtCidadeEnder.setBackground(new java.awt.Color(204, 204, 204));
        txtCidadeEnder.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCidadeEnder.setForeground(new java.awt.Color(0, 0, 0));
        txtCidadeEnder.setBorder(new javax.swing.border.MatteBorder(null));

        txtBairroEnder.setBackground(new java.awt.Color(204, 204, 204));
        txtBairroEnder.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBairroEnder.setForeground(new java.awt.Color(0, 0, 0));
        txtBairroEnder.setBorder(new javax.swing.border.MatteBorder(null));

        jlCEPVendedor.setBackground(new java.awt.Color(0, 0, 0));
        jlCEPVendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlCEPVendedor.setForeground(new java.awt.Color(0, 0, 0));
        jlCEPVendedor.setText("CEP:");

        txtNomeRevendedor.setBackground(new java.awt.Color(204, 204, 204));
        txtNomeRevendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNomeRevendedor.setForeground(new java.awt.Color(0, 0, 0));
        txtNomeRevendedor.setBorder(new javax.swing.border.MatteBorder(null));

        jpDataValorCompra.setBackground(new java.awt.Color(255, 255, 102));
        jpDataValorCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        jlDataCompra.setBackground(new java.awt.Color(0, 0, 0));
        jlDataCompra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlDataCompra.setForeground(new java.awt.Color(204, 0, 0));
        jlDataCompra.setText("Data da compra:");

        txtDataCompra.setBackground(new java.awt.Color(204, 204, 204));
        txtDataCompra.setBorder(new javax.swing.border.MatteBorder(null));
        txtDataCompra.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtDataCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataCompra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jlValorCompra.setBackground(new java.awt.Color(0, 0, 0));
        jlValorCompra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlValorCompra.setForeground(new java.awt.Color(204, 0, 0));
        jlValorCompra.setText("Valor da compra:");

        txtValorCompra.setBackground(new java.awt.Color(204, 204, 204));
        txtValorCompra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtValorCompra.setForeground(new java.awt.Color(0, 0, 0));
        txtValorCompra.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jpDataValorCompraLayout = new javax.swing.GroupLayout(jpDataValorCompra);
        jpDataValorCompra.setLayout(jpDataValorCompraLayout);
        jpDataValorCompraLayout.setHorizontalGroup(
            jpDataValorCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDataValorCompraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpDataValorCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDataValorCompraLayout.createSequentialGroup()
                        .addComponent(jlDataCompra)
                        .addGap(22, 22, 22)
                        .addComponent(txtDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDataValorCompraLayout.createSequentialGroup()
                        .addComponent(jlValorCompra)
                        .addGap(18, 18, 18)
                        .addComponent(txtValorCompra))))
        );
        jpDataValorCompraLayout.setVerticalGroup(
            jpDataValorCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDataValorCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDataValorCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDataCompra)
                    .addComponent(txtDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpDataValorCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValorCompra)
                    .addComponent(txtValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        txtEstadoEnd.setBackground(new java.awt.Color(204, 204, 204));
        txtEstadoEnd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEstadoEnd.setForeground(new java.awt.Color(0, 0, 0));
        txtEstadoEnd.setBorder(new javax.swing.border.MatteBorder(null));

        jlCEPVendedor1.setBackground(new java.awt.Color(0, 0, 0));
        jlCEPVendedor1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlCEPVendedor1.setForeground(new java.awt.Color(0, 0, 0));
        jlCEPVendedor1.setText("CPF:");

        txtCpfRevendedor.setBackground(new java.awt.Color(204, 204, 204));
        txtCpfRevendedor.setBorder(new javax.swing.border.MatteBorder(null));
        txtCpfRevendedor.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtCpfRevendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfRevendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jpVendedorLayout = new javax.swing.GroupLayout(jpVendedor);
        jpVendedor.setLayout(jpVendedorLayout);
        jpVendedorLayout.setHorizontalGroup(
            jpVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpVendedorLayout.createSequentialGroup()
                        .addGroup(jpVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpVendedorLayout.createSequentialGroup()
                                .addComponent(jpDataValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jpVendedorLayout.createSequentialGroup()
                                .addGroup(jpVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNomeVendedor)
                                    .addComponent(jlTelVendedor)
                                    .addComponent(jlEndVendedor)
                                    .addComponent(jlCEPVendedor)
                                    .addComponent(jlBairroVendedor)
                                    .addComponent(jlCidadeVendedor)
                                    .addComponent(jlEstadoVendedor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCidadeEnder)
                                    .addComponent(txtBairroEnder)
                                    .addComponent(txtDescEndereco)
                                    .addGroup(jpVendedorLayout.createSequentialGroup()
                                        .addGroup(jpVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTelRevendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(txtCepRevendedor))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                        .addComponent(jlNumEndVendedor)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNumEndRevendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNomeRevendedor)
                                    .addComponent(txtEstadoEnd, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(3, 3, 3))
                    .addGroup(jpVendedorLayout.createSequentialGroup()
                        .addComponent(jlCEPVendedor1)
                        .addGap(109, 109, 109)
                        .addComponent(txtCpfRevendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpVendedorLayout.setVerticalGroup(
            jpVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVendedorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeVendedor)
                    .addComponent(txtNomeRevendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelVendedor)
                    .addComponent(txtTelRevendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jpVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpfRevendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCEPVendedor1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumEndVendedor)
                    .addComponent(txtCepRevendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCEPVendedor)
                    .addComponent(txtNumEndRevendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEndVendedor)
                    .addComponent(txtDescEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBairroVendedor)
                    .addComponent(txtBairroEnder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCidadeVendedor)
                    .addComponent(txtCidadeEnder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEstadoVendedor)
                    .addComponent(txtEstadoEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jpDataValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpVeiculo.setBackground(new java.awt.Color(255, 255, 102));
        jpVeiculo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Veículo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24), new java.awt.Color(0, 0, 0))); // NOI18N

        jlPlacaVeiculoCompra.setBackground(new java.awt.Color(0, 0, 0));
        jlPlacaVeiculoCompra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlPlacaVeiculoCompra.setForeground(new java.awt.Color(0, 0, 0));
        jlPlacaVeiculoCompra.setText("Placa:");

        txtPlaca.setBackground(new java.awt.Color(204, 204, 204));
        txtPlaca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPlaca.setForeground(new java.awt.Color(0, 0, 0));
        txtPlaca.setBorder(new javax.swing.border.MatteBorder(null));

        jlRenavamVeiculoCompra.setBackground(new java.awt.Color(0, 0, 0));
        jlRenavamVeiculoCompra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlRenavamVeiculoCompra.setForeground(new java.awt.Color(0, 0, 0));
        jlRenavamVeiculoCompra.setText("Renavam:");

        txtRenavam.setBackground(new java.awt.Color(204, 204, 204));
        txtRenavam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtRenavam.setForeground(new java.awt.Color(0, 0, 0));
        txtRenavam.setBorder(new javax.swing.border.MatteBorder(null));

        jlMarcaVeiculoCompra.setBackground(new java.awt.Color(0, 0, 0));
        jlMarcaVeiculoCompra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlMarcaVeiculoCompra.setForeground(new java.awt.Color(0, 0, 0));
        jlMarcaVeiculoCompra.setText("Marca:");

        jlModeloVeiculoCompra.setBackground(new java.awt.Color(0, 0, 0));
        jlModeloVeiculoCompra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlModeloVeiculoCompra.setForeground(new java.awt.Color(0, 0, 0));
        jlModeloVeiculoCompra.setText("Modelo:");

        txtModelo.setBackground(new java.awt.Color(204, 204, 204));
        txtModelo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtModelo.setForeground(new java.awt.Color(0, 0, 0));
        txtModelo.setBorder(new javax.swing.border.MatteBorder(null));

        txtMarca.setBackground(new java.awt.Color(204, 204, 204));
        txtMarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMarca.setForeground(new java.awt.Color(0, 0, 0));
        txtMarca.setBorder(new javax.swing.border.MatteBorder(null));

        jlAnoVeiculoCompra.setBackground(new java.awt.Color(0, 0, 0));
        jlAnoVeiculoCompra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlAnoVeiculoCompra.setForeground(new java.awt.Color(0, 0, 0));
        jlAnoVeiculoCompra.setText("Ano:");

        txtAno.setBackground(new java.awt.Color(204, 204, 204));
        txtAno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAno.setForeground(new java.awt.Color(0, 0, 0));
        txtAno.setBorder(new javax.swing.border.MatteBorder(null));

        jpTipoVeiculoCompra.setBackground(new java.awt.Color(255, 255, 102));
        jpTipoVeiculoCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jpTipoVeiculoCompra.setForeground(new java.awt.Color(0, 0, 0));

        jrbCarro.setBackground(new java.awt.Color(255, 255, 102));
        bgTipo.add(jrbCarro);
        jrbCarro.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jrbCarro.setForeground(new java.awt.Color(0, 0, 0));
        jrbCarro.setMnemonic('C');
        jrbCarro.setText("Carro");

        jrbMoto.setBackground(new java.awt.Color(255, 255, 102));
        bgTipo.add(jrbMoto);
        jrbMoto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jrbMoto.setForeground(new java.awt.Color(0, 0, 0));
        jrbMoto.setMnemonic('M');
        jrbMoto.setText("Moto");

        javax.swing.GroupLayout jpTipoVeiculoCompraLayout = new javax.swing.GroupLayout(jpTipoVeiculoCompra);
        jpTipoVeiculoCompra.setLayout(jpTipoVeiculoCompraLayout);
        jpTipoVeiculoCompraLayout.setHorizontalGroup(
            jpTipoVeiculoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTipoVeiculoCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTipoVeiculoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbCarro)
                    .addComponent(jrbMoto))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jpTipoVeiculoCompraLayout.setVerticalGroup(
            jpTipoVeiculoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTipoVeiculoCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbCarro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbMoto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlCorVeiculoCompra.setBackground(new java.awt.Color(0, 0, 0));
        jlCorVeiculoCompra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlCorVeiculoCompra.setForeground(new java.awt.Color(0, 0, 0));
        jlCorVeiculoCompra.setText("Cor:");

        cmbCor.setBackground(new java.awt.Color(204, 204, 204));
        cmbCor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbCor.setForeground(new java.awt.Color(0, 0, 0));
        cmbCor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preto", "Prata", "Branco", "Vermelho", "Cinza", "Verde", "Azul", "Amarelo", "Rosa", "Roxo", "Marrom" }));
        cmbCor.setBorder(null);
        cmbCor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jpCombustivelVeiculoCompra.setBackground(new java.awt.Color(255, 255, 102));
        jpCombustivelVeiculoCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Combustível", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jpCombustivelVeiculoCompra.setForeground(new java.awt.Color(0, 0, 0));

        jrbGasolina.setBackground(new java.awt.Color(255, 255, 102));
        bgCombustivel.add(jrbGasolina);
        jrbGasolina.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jrbGasolina.setForeground(new java.awt.Color(0, 0, 0));
        jrbGasolina.setText("Gasolina");

        jrbDiesel.setBackground(new java.awt.Color(255, 255, 102));
        bgCombustivel.add(jrbDiesel);
        jrbDiesel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jrbDiesel.setForeground(new java.awt.Color(0, 0, 0));
        jrbDiesel.setText("Diesel");

        jrbEtanol.setBackground(new java.awt.Color(255, 255, 102));
        bgCombustivel.add(jrbEtanol);
        jrbEtanol.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jrbEtanol.setForeground(new java.awt.Color(0, 0, 0));
        jrbEtanol.setText("Etanol");

        jrbGas.setBackground(new java.awt.Color(255, 255, 102));
        bgCombustivel.add(jrbGas);
        jrbGas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jrbGas.setForeground(new java.awt.Color(0, 0, 0));
        jrbGas.setText("Gás");

        jrbFlex.setBackground(new java.awt.Color(255, 255, 102));
        bgCombustivel.add(jrbFlex);
        jrbFlex.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jrbFlex.setForeground(new java.awt.Color(0, 0, 0));
        jrbFlex.setText("Flex");

        jrbEletrico.setBackground(new java.awt.Color(255, 255, 102));
        bgCombustivel.add(jrbEletrico);
        jrbEletrico.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jrbEletrico.setForeground(new java.awt.Color(0, 0, 0));
        jrbEletrico.setText("Elétrico");

        jrbHibrido.setBackground(new java.awt.Color(255, 255, 102));
        bgCombustivel.add(jrbHibrido);
        jrbHibrido.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jrbHibrido.setForeground(new java.awt.Color(0, 0, 0));
        jrbHibrido.setText("Híbrido");

        javax.swing.GroupLayout jpCombustivelVeiculoCompraLayout = new javax.swing.GroupLayout(jpCombustivelVeiculoCompra);
        jpCombustivelVeiculoCompra.setLayout(jpCombustivelVeiculoCompraLayout);
        jpCombustivelVeiculoCompraLayout.setHorizontalGroup(
            jpCombustivelVeiculoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCombustivelVeiculoCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCombustivelVeiculoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jrbEletrico)
                    .addGroup(jpCombustivelVeiculoCompraLayout.createSequentialGroup()
                        .addGroup(jpCombustivelVeiculoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbGasolina)
                            .addComponent(jrbDiesel)
                            .addComponent(jrbEtanol)
                            .addComponent(jrbGas))
                        .addGap(18, 18, 18)
                        .addGroup(jpCombustivelVeiculoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbHibrido)
                            .addComponent(jrbFlex))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jpCombustivelVeiculoCompraLayout.setVerticalGroup(
            jpCombustivelVeiculoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCombustivelVeiculoCompraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpCombustivelVeiculoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbGasolina)
                    .addComponent(jrbFlex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCombustivelVeiculoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbDiesel)
                    .addComponent(jrbEletrico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCombustivelVeiculoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbEtanol)
                    .addComponent(jrbHibrido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbGas)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpVeiculoLayout = new javax.swing.GroupLayout(jpVeiculo);
        jpVeiculo.setLayout(jpVeiculoLayout);
        jpVeiculoLayout.setHorizontalGroup(
            jpVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpVeiculoLayout.createSequentialGroup()
                        .addGroup(jpVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlPlacaVeiculoCompra)
                            .addComponent(jlRenavamVeiculoCompra)
                            .addComponent(jlMarcaVeiculoCompra)
                            .addComponent(jlModeloVeiculoCompra)
                            .addComponent(jlAnoVeiculoCompra))
                        .addGap(31, 31, 31)
                        .addGroup(jpVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRenavam)
                            .addComponent(txtMarca)
                            .addGroup(jpVeiculoLayout.createSequentialGroup()
                                .addGroup(jpVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPlaca)
                                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtModelo))
                        .addGap(28, 28, 28)
                        .addComponent(jpTipoVeiculoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpVeiculoLayout.createSequentialGroup()
                        .addComponent(jlCorVeiculoCompra)
                        .addGap(12, 12, 12)
                        .addComponent(cmbCor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpCombustivelVeiculoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpVeiculoLayout.setVerticalGroup(
            jpVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVeiculoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpTipoVeiculoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpVeiculoLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jpVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPlacaVeiculoCompra)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlRenavamVeiculoCompra)
                            .addComponent(txtRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlMarcaVeiculoCompra)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlModeloVeiculoCompra)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlAnoVeiculoCompra)
                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jpVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpCombustivelVeiculoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpVeiculoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jpVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCorVeiculoCompra))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbRegistrarCompra.setBackground(new java.awt.Color(51, 51, 51));
        jbRegistrarCompra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbRegistrarCompra.setForeground(new java.awt.Color(255, 255, 255));
        jbRegistrarCompra.setText("Registrar");
        jbRegistrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpNovaCompraLayout = new javax.swing.GroupLayout(jpNovaCompra);
        jpNovaCompra.setLayout(jpNovaCompraLayout);
        jpNovaCompraLayout.setHorizontalGroup(
            jpNovaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNovaCompraLayout.createSequentialGroup()
                .addGroup(jpNovaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNovaCompraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpNovaCompraLayout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(jbRegistrarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jpNovaCompraLayout.setVerticalGroup(
            jpNovaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNovaCompraLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpNovaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jbRegistrarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jtPainelCompra.addTab("Nova", jpNovaCompra);

        jpListaVeiculosComprados.setBackground(new java.awt.Color(255, 255, 102));
        jpListaVeiculosComprados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpListaVeiculosComprados.setForeground(new java.awt.Color(0, 0, 0));

        jtListaVeiculosComprados.setBackground(new java.awt.Color(204, 204, 204));
        jtListaVeiculosComprados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vendedor", "Tipo", "Placa", "Renavam", "Marca", "Modelo", "Ano", "Cor", "Combustível", "Data Compra", "Valor"
            }
        ));
        jsListaVeiculosComprados.setViewportView(jtListaVeiculosComprados);

        jlPlacaFiltroDespesas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlPlacaFiltroDespesas.setForeground(new java.awt.Color(0, 0, 0));
        jlPlacaFiltroDespesas.setText("Placa:");

        jtPlacaFiltroDespesas.setBackground(new java.awt.Color(204, 204, 204));
        jtPlacaFiltroDespesas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtPlacaFiltroDespesas.setBorder(new javax.swing.border.MatteBorder(null));

        jbPesquisarFiltroDespesas.setBackground(new java.awt.Color(51, 51, 51));
        jbPesquisarFiltroDespesas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbPesquisarFiltroDespesas.setForeground(new java.awt.Color(255, 255, 255));
        jbPesquisarFiltroDespesas.setText("Pesquisar");

        jbListarFiltroDespesas.setBackground(new java.awt.Color(51, 51, 51));
        jbListarFiltroDespesas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbListarFiltroDespesas.setForeground(new java.awt.Color(255, 255, 255));
        jbListarFiltroDespesas.setText("Listar Todas");

        javax.swing.GroupLayout jpListaVeiculosCompradosLayout = new javax.swing.GroupLayout(jpListaVeiculosComprados);
        jpListaVeiculosComprados.setLayout(jpListaVeiculosCompradosLayout);
        jpListaVeiculosCompradosLayout.setHorizontalGroup(
            jpListaVeiculosCompradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListaVeiculosCompradosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpListaVeiculosCompradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsListaVeiculosComprados, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
                    .addGroup(jpListaVeiculosCompradosLayout.createSequentialGroup()
                        .addComponent(jlPlacaFiltroDespesas)
                        .addGap(18, 18, 18)
                        .addComponent(jtPlacaFiltroDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbPesquisarFiltroDespesas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                        .addComponent(jbListarFiltroDespesas)))
                .addContainerGap())
        );
        jpListaVeiculosCompradosLayout.setVerticalGroup(
            jpListaVeiculosCompradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpListaVeiculosCompradosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpListaVeiculosCompradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPlacaFiltroDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPlacaFiltroDespesas)
                    .addComponent(jbListarFiltroDespesas)
                    .addComponent(jbPesquisarFiltroDespesas))
                .addGap(18, 18, 18)
                .addComponent(jsListaVeiculosComprados, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtPainelCompra.addTab("Comprados", jpListaVeiculosComprados);

        javax.swing.GroupLayout jpPrincipalCompraLayout = new javax.swing.GroupLayout(jpPrincipalCompra);
        jpPrincipalCompra.setLayout(jpPrincipalCompraLayout);
        jpPrincipalCompraLayout.setHorizontalGroup(
            jpPrincipalCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalCompraLayout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jlTituloCompra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpPrincipalCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtPainelCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpPrincipalCompraLayout.setVerticalGroup(
            jpPrincipalCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTituloCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtPainelCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jpPrincipalCompra, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbRegistrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarCompraActionPerformed

        // INFORMAÇÕES DO REVENDEDOR
        String nome = txtNomeRevendedor.getText();
        String telefone = txtTelRevendedor.getText();
        String cpf = txtCpfRevendedor.getText();
        String cep = txtCepRevendedor.getText();
        String txtNumero = txtNumEndRevendedor.getText();
        String descricao = txtDescEndereco.getText();
        String bairro = txtBairroEnder.getText();
        String cidade = txtCidadeEnder.getText();
        String estado = txtEstadoEnd.getText();

        // INFORMAÇÕES DA COMPRA
        String dataCompra = txtDataCompra.getText();
        String valorCompra = txtValorCompra.getText();

        // INFORMAÇÕES DO VEICULO 
        String placa = txtPlaca.getText();
        String tRenavam = txtRenavam.getText();
        String marca = txtMarca.getText();
        String modelo = txtModelo.getText();
        String tAno = txtAno.getText();
        String cor = (String) cmbCor.getSelectedItem();
        String tipoVeiculo = bgTipo.getSelection().getActionCommand();
        String combustivel = bgCombustivel.getSelection().getActionCommand();

        try {
            // INSERIR NO BANCO

            int num = Integer.parseInt(txtNumero);
            int renavam = Integer.parseInt(tRenavam);
            int ano = Integer.parseInt(tAno);
            double valor = Double.parseDouble(valorCompra);
            Date data = FuncoesUteis.strToDate(dataCompra);
            
            Endereco endereco = new Endereco(cep, bairro, descricao, num, cidade, estado);
            Pessoa revendedor = new Pessoa(nome, telefone, endereco);
            Veiculo veiculo = new Veiculo(placa, renavam, marca, modelo, cor, tipoVeiculo, combustivel, ano);
            
            Compra compra = GerenciadorInterface.getInstance().getGerenciadorDominio().inserirCompra( valor, data, revendedor, veiculo );

            JOptionPane.showMessageDialog(this, "Compra inserida com sucesso.", "Cadastro Compra", JOptionPane.INFORMATION_MESSAGE);

        } catch (HibernateException ex) {
            JOptionPane.showMessageDialog(this, "Erro nos dados. " + ex.getMessage(), "ERRO Cadastro Compra", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException ex) {
            Logger.getLogger(DlgCompra.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jbRegistrarCompraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCombustivel;
    private javax.swing.ButtonGroup bgTipo;
    private javax.swing.JComboBox<String> cmbCor;
    private javax.swing.JButton jbListarFiltroDespesas;
    private javax.swing.JButton jbPesquisarFiltroDespesas;
    private javax.swing.JButton jbRegistrarCompra;
    private javax.swing.JLabel jlAnoVeiculoCompra;
    private javax.swing.JLabel jlBairroVendedor;
    private javax.swing.JLabel jlCEPVendedor;
    private javax.swing.JLabel jlCEPVendedor1;
    private javax.swing.JLabel jlCidadeVendedor;
    private javax.swing.JLabel jlCorVeiculoCompra;
    private javax.swing.JLabel jlDataCompra;
    private javax.swing.JLabel jlEndVendedor;
    private javax.swing.JLabel jlEstadoVendedor;
    private javax.swing.JLabel jlMarcaVeiculoCompra;
    private javax.swing.JLabel jlModeloVeiculoCompra;
    private javax.swing.JLabel jlNomeVendedor;
    private javax.swing.JLabel jlNumEndVendedor;
    private javax.swing.JLabel jlPlacaFiltroDespesas;
    private javax.swing.JLabel jlPlacaVeiculoCompra;
    private javax.swing.JLabel jlRenavamVeiculoCompra;
    private javax.swing.JLabel jlTelVendedor;
    private javax.swing.JLabel jlTituloCompra;
    private javax.swing.JLabel jlValorCompra;
    private javax.swing.JPanel jpCombustivelVeiculoCompra;
    private javax.swing.JPanel jpDataValorCompra;
    private javax.swing.JPanel jpListaVeiculosComprados;
    private javax.swing.JPanel jpNovaCompra;
    private javax.swing.JPanel jpPrincipalCompra;
    private javax.swing.JPanel jpTipoVeiculoCompra;
    private javax.swing.JPanel jpVeiculo;
    private javax.swing.JPanel jpVendedor;
    private javax.swing.JRadioButton jrbCarro;
    private javax.swing.JRadioButton jrbDiesel;
    private javax.swing.JRadioButton jrbEletrico;
    private javax.swing.JRadioButton jrbEtanol;
    private javax.swing.JRadioButton jrbFlex;
    private javax.swing.JRadioButton jrbGas;
    private javax.swing.JRadioButton jrbGasolina;
    private javax.swing.JRadioButton jrbHibrido;
    private javax.swing.JRadioButton jrbMoto;
    private javax.swing.JScrollPane jsListaVeiculosComprados;
    private javax.swing.JTable jtListaVeiculosComprados;
    private javax.swing.JTabbedPane jtPainelCompra;
    private javax.swing.JTextField jtPlacaFiltroDespesas;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtBairroEnder;
    private javax.swing.JFormattedTextField txtCepRevendedor;
    private javax.swing.JTextField txtCidadeEnder;
    private javax.swing.JFormattedTextField txtCpfRevendedor;
    private javax.swing.JFormattedTextField txtDataCompra;
    private javax.swing.JTextField txtDescEndereco;
    private javax.swing.JTextField txtEstadoEnd;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNomeRevendedor;
    private javax.swing.JTextField txtNumEndRevendedor;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtRenavam;
    private javax.swing.JFormattedTextField txtTelRevendedor;
    private javax.swing.JTextField txtValorCompra;
    // End of variables declaration//GEN-END:variables
}
