/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package viewer;

/**
 *
 * @author 2022122760044
 */
public class DlgDespesas extends javax.swing.JDialog {

    /**
     * Creates new form DlgConsulta
     */
    public DlgDespesas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrincipalDespesas = new javax.swing.JPanel();
        jlTituloDespesas = new javax.swing.JLabel();
        jtPainelDespesas = new javax.swing.JTabbedPane();
        jpNovaDespesa = new javax.swing.JPanel();
        jpSelecionarVeiculoDespesa = new javax.swing.JPanel();
        jlPlaca = new javax.swing.JLabel();
        jtPlaca = new javax.swing.JTextField();
        jbListarVeiculos = new javax.swing.JButton();
        jbPesquisar = new javax.swing.JButton();
        jpVeiculosDespesa = new javax.swing.JPanel();
        jsVeiculoDespesa = new javax.swing.JScrollPane();
        jtVeiculoDespesa = new javax.swing.JTable();
        jpDespesas = new javax.swing.JPanel();
        jlDescricao = new javax.swing.JLabel();
        jtDescricao = new javax.swing.JTextField();
        jlValorDespesa = new javax.swing.JLabel();
        jtValorDespesa = new javax.swing.JTextField();
        jbAddDespesa = new javax.swing.JButton();
        jpListaDespesa = new javax.swing.JPanel();
        jpListaDepesas = new javax.swing.JPanel();
        jsListaDespesasVeiculos = new javax.swing.JScrollPane();
        jtListaDespesasVeiculos = new javax.swing.JTable();
        jlPlacaFiltroDespesas = new javax.swing.JLabel();
        jtPlacaFiltroDespesas = new javax.swing.JTextField();
        jbPesquisarFiltroDespesas = new javax.swing.JButton();
        jbListarFiltroDespesas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Despesas");
        setResizable(false);

        jpPrincipalDespesas.setBackground(new java.awt.Color(255, 255, 102));

        jlTituloDespesas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jlTituloDespesas.setForeground(new java.awt.Color(0, 0, 0));
        jlTituloDespesas.setText("REGISTRO DE DESPESAS");

        jtPainelDespesas.setBackground(new java.awt.Color(51, 51, 51));
        jtPainelDespesas.setForeground(new java.awt.Color(255, 255, 255));
        jtPainelDespesas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jpNovaDespesa.setBackground(new java.awt.Color(255, 255, 102));
        jpNovaDespesa.setBorder(new javax.swing.border.MatteBorder(null));
        jpNovaDespesa.setForeground(new java.awt.Color(51, 51, 51));

        jpSelecionarVeiculoDespesa.setBackground(new java.awt.Color(255, 255, 102));
        jpSelecionarVeiculoDespesa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Selecione um veículo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        jpSelecionarVeiculoDespesa.setForeground(new java.awt.Color(0, 0, 0));

        jlPlaca.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlPlaca.setForeground(new java.awt.Color(0, 0, 0));
        jlPlaca.setText("Placa:");

        jtPlaca.setBackground(new java.awt.Color(204, 204, 204));
        jtPlaca.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtPlaca.setBorder(new javax.swing.border.MatteBorder(null));

        jbListarVeiculos.setBackground(new java.awt.Color(51, 51, 51));
        jbListarVeiculos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbListarVeiculos.setForeground(new java.awt.Color(255, 255, 255));
        jbListarVeiculos.setText("Listar Veículos");

        jbPesquisar.setBackground(new java.awt.Color(51, 51, 51));
        jbPesquisar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jbPesquisar.setText("Pesquisar");

        jpVeiculosDespesa.setBackground(new java.awt.Color(255, 255, 102));

        jtVeiculoDespesa.setBackground(new java.awt.Color(204, 204, 204));
        jtVeiculoDespesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Marca", "Modelo", "Cor"
            }
        ));
        jsVeiculoDespesa.setViewportView(jtVeiculoDespesa);

        javax.swing.GroupLayout jpVeiculosDespesaLayout = new javax.swing.GroupLayout(jpVeiculosDespesa);
        jpVeiculosDespesa.setLayout(jpVeiculosDespesaLayout);
        jpVeiculosDespesaLayout.setHorizontalGroup(
            jpVeiculosDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVeiculosDespesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jsVeiculoDespesa)
                .addContainerGap())
        );
        jpVeiculosDespesaLayout.setVerticalGroup(
            jpVeiculosDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVeiculosDespesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jsVeiculoDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpSelecionarVeiculoDespesaLayout = new javax.swing.GroupLayout(jpSelecionarVeiculoDespesa);
        jpSelecionarVeiculoDespesa.setLayout(jpSelecionarVeiculoDespesaLayout);
        jpSelecionarVeiculoDespesaLayout.setHorizontalGroup(
            jpSelecionarVeiculoDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSelecionarVeiculoDespesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSelecionarVeiculoDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpVeiculosDespesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpSelecionarVeiculoDespesaLayout.createSequentialGroup()
                        .addComponent(jlPlaca)
                        .addGap(18, 18, 18)
                        .addComponent(jtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbListarVeiculos)))
                .addContainerGap())
        );
        jpSelecionarVeiculoDespesaLayout.setVerticalGroup(
            jpSelecionarVeiculoDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSelecionarVeiculoDespesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSelecionarVeiculoDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPlaca)
                    .addComponent(jbListarVeiculos)
                    .addComponent(jbPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jpVeiculosDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpDespesas.setBackground(new java.awt.Color(255, 255, 102));
        jpDespesas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Despesa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        jpDespesas.setForeground(new java.awt.Color(0, 0, 0));

        jlDescricao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlDescricao.setForeground(new java.awt.Color(0, 0, 0));
        jlDescricao.setText("Descrição:");

        jtDescricao.setBackground(new java.awt.Color(204, 204, 204));
        jtDescricao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtDescricao.setBorder(new javax.swing.border.MatteBorder(null));

        jlValorDespesa.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlValorDespesa.setForeground(new java.awt.Color(0, 0, 0));
        jlValorDespesa.setText("Valor:");

        jtValorDespesa.setBackground(new java.awt.Color(204, 204, 204));
        jtValorDespesa.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtValorDespesa.setBorder(new javax.swing.border.MatteBorder(null));

        jbAddDespesa.setBackground(new java.awt.Color(51, 51, 51));
        jbAddDespesa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbAddDespesa.setForeground(new java.awt.Color(255, 255, 255));
        jbAddDespesa.setText("Adicionar");

        javax.swing.GroupLayout jpDespesasLayout = new javax.swing.GroupLayout(jpDespesas);
        jpDespesas.setLayout(jpDespesasLayout);
        jpDespesasLayout.setHorizontalGroup(
            jpDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDespesasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlDescricao)
                .addGap(18, 18, 18)
                .addComponent(jtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jlValorDespesa)
                .addGap(18, 18, 18)
                .addComponent(jtValorDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jpDespesasLayout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(jbAddDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpDespesasLayout.setVerticalGroup(
            jpDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDespesasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDescricao)
                    .addComponent(jtValorDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlValorDespesa))
                .addGap(18, 18, 18)
                .addComponent(jbAddDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpNovaDespesaLayout = new javax.swing.GroupLayout(jpNovaDespesa);
        jpNovaDespesa.setLayout(jpNovaDespesaLayout);
        jpNovaDespesaLayout.setHorizontalGroup(
            jpNovaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNovaDespesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpNovaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpSelecionarVeiculoDespesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpNovaDespesaLayout.setVerticalGroup(
            jpNovaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNovaDespesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpSelecionarVeiculoDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jtPainelDespesas.addTab("Nova", jpNovaDespesa);

        jpListaDespesa.setBackground(new java.awt.Color(255, 255, 102));
        jpListaDespesa.setBorder(new javax.swing.border.MatteBorder(null));
        jpListaDespesa.setForeground(new java.awt.Color(51, 51, 51));

        jpListaDepesas.setBackground(new java.awt.Color(255, 255, 102));

        jtListaDespesasVeiculos.setBackground(new java.awt.Color(204, 204, 204));
        jtListaDespesasVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Marca", "Modelo", "Cor", "Despesa", "Valor"
            }
        ));
        jsListaDespesasVeiculos.setViewportView(jtListaDespesasVeiculos);

        jlPlacaFiltroDespesas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlPlacaFiltroDespesas.setForeground(new java.awt.Color(0, 0, 0));
        jlPlacaFiltroDespesas.setText("Placa:");

        jtPlacaFiltroDespesas.setBackground(new java.awt.Color(204, 204, 204));
        jtPlacaFiltroDespesas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtPlacaFiltroDespesas.setBorder(new javax.swing.border.MatteBorder(null));

        jbPesquisarFiltroDespesas.setBackground(new java.awt.Color(51, 51, 51));
        jbPesquisarFiltroDespesas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbPesquisarFiltroDespesas.setForeground(new java.awt.Color(255, 255, 255));
        jbPesquisarFiltroDespesas.setText("Pesquisar");

        jbListarFiltroDespesas.setBackground(new java.awt.Color(51, 51, 51));
        jbListarFiltroDespesas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbListarFiltroDespesas.setForeground(new java.awt.Color(255, 255, 255));
        jbListarFiltroDespesas.setText("Listar Todas");

        javax.swing.GroupLayout jpListaDepesasLayout = new javax.swing.GroupLayout(jpListaDepesas);
        jpListaDepesas.setLayout(jpListaDepesasLayout);
        jpListaDepesasLayout.setHorizontalGroup(
            jpListaDepesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListaDepesasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpListaDepesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsListaDespesasVeiculos)
                    .addGroup(jpListaDepesasLayout.createSequentialGroup()
                        .addComponent(jlPlacaFiltroDespesas)
                        .addGap(18, 18, 18)
                        .addComponent(jtPlacaFiltroDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbPesquisarFiltroDespesas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                        .addComponent(jbListarFiltroDespesas)))
                .addContainerGap())
        );
        jpListaDepesasLayout.setVerticalGroup(
            jpListaDepesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpListaDepesasLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jpListaDepesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPlacaFiltroDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPlacaFiltroDespesas)
                    .addComponent(jbListarFiltroDespesas)
                    .addComponent(jbPesquisarFiltroDespesas))
                .addGap(18, 18, 18)
                .addComponent(jsListaDespesasVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpListaDespesaLayout = new javax.swing.GroupLayout(jpListaDespesa);
        jpListaDespesa.setLayout(jpListaDespesaLayout);
        jpListaDespesaLayout.setHorizontalGroup(
            jpListaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListaDespesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpListaDepesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpListaDespesaLayout.setVerticalGroup(
            jpListaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListaDespesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpListaDepesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtPainelDespesas.addTab("Despesas", jpListaDespesa);

        javax.swing.GroupLayout jpPrincipalDespesasLayout = new javax.swing.GroupLayout(jpPrincipalDespesas);
        jpPrincipalDespesas.setLayout(jpPrincipalDespesasLayout);
        jpPrincipalDespesasLayout.setHorizontalGroup(
            jpPrincipalDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalDespesasLayout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jlTituloDespesas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrincipalDespesasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtPainelDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpPrincipalDespesasLayout.setVerticalGroup(
            jpPrincipalDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalDespesasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTituloDespesas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtPainelDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jpPrincipalDespesas, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgDespesas dialog = new DlgDespesas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAddDespesa;
    private javax.swing.JButton jbListarFiltroDespesas;
    private javax.swing.JButton jbListarVeiculos;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbPesquisarFiltroDespesas;
    private javax.swing.JLabel jlDescricao;
    private javax.swing.JLabel jlPlaca;
    private javax.swing.JLabel jlPlacaFiltroDespesas;
    private javax.swing.JLabel jlTituloDespesas;
    private javax.swing.JLabel jlValorDespesa;
    private javax.swing.JPanel jpDespesas;
    private javax.swing.JPanel jpListaDepesas;
    private javax.swing.JPanel jpListaDespesa;
    private javax.swing.JPanel jpNovaDespesa;
    private javax.swing.JPanel jpPrincipalDespesas;
    private javax.swing.JPanel jpSelecionarVeiculoDespesa;
    private javax.swing.JPanel jpVeiculosDespesa;
    private javax.swing.JScrollPane jsListaDespesasVeiculos;
    private javax.swing.JScrollPane jsVeiculoDespesa;
    private javax.swing.JTextField jtDescricao;
    private javax.swing.JTable jtListaDespesasVeiculos;
    private javax.swing.JTabbedPane jtPainelDespesas;
    private javax.swing.JTextField jtPlaca;
    private javax.swing.JTextField jtPlacaFiltroDespesas;
    private javax.swing.JTextField jtValorDespesa;
    private javax.swing.JTable jtVeiculoDespesa;
    // End of variables declaration//GEN-END:variables
}
